# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K5WiEYe8gICyxwc3oO40wGP9GVqtttq2
"""

import random
import time

class BGMISimulator:
    def __init__(self, players_count=100):
        self.players = [{"id": i, "hp": 100, "alive": True, "kills": 0, "loot": "None"} for i in range(players_count)]
        self.zone_radius = 1000  # Starting zone size in meters
        self.timer = 0

    def start_game(self):
        print("🪂 All players have jumped from the plane! Game Start.")
        while self.count_alive() > 1:
            self.game_tick()
            time.sleep(0.5) # Speed up simulation

        winner = next(p for p in self.players if p['alive'])
        print(f"\n🏆 WINNER WINNER CHICKEN DINNER! 🏆")
        print(f"Player {winner['id']} won with {winner['kills']} kills!")

    def game_tick(self):
        self.timer += 1
        # 1. Shrink Zone
        if self.timer % 5 == 0:
            self.zone_radius -= 150
            print(f"⚠️ Zone is shrinking! Current Radius: {max(0, self.zone_radius)}m")

        # 2. Random Encounters
        p1, p2 = random.sample([p for p in self.players if p['alive']], 2)
        self.combat(p1, p2)

    def combat(self, p1, p2):
        # Simple combat logic
        weapon_damage = random.randint(20, 60)
        p2['hp'] -= weapon_damage

        if p2['hp'] <= 0:
            p2['alive'] = False
            p1['kills'] += 1
            print(f"🔫 Player {p1['id']} knocked out Player {p2['id']}! (Alive: {self.count_alive()})")

    def count_alive(self):
        return sum(1 for p in self.players if p['alive'])

# Run the game in Colab
game = BGMISimulator(100)
game.start_game()